### ISSUE TITLE
/advantage checkout - add messaging explaining proration when price is prorated

### ISSUE THREAD

**Issue by ajbeattie** [canonical-web-and-design/ubuntu.com#8481] opened 2020-10-15 14:27 UTC
## Summary

When making a purchase at /advantage after a past purchase has already been made (and thus a subscription is already active in Stripe), it is unclear how/why the proration is applied to the price. It would be helpful to message that the price displayed is prorated (and maybe a tooltip explaining why) when this is the case.

## Process

- Make a purchase at /advantage
- Make another purchase and note the price will be slightly lower

## Current and expected result

Current: the prorated price is shown with no explanation as to why it's different

Expected: the prorated price is listed as a 'Prorated price' (perhaps with the list price also listed separately), and a tool tip or similar is available which explains something like `This purchase will be added to your existing subscription, so it is prorated to match your current billing cycle`

**Comment by SirSamTumless** [comment] 2020-10-20 10:24
@matthewpaulthomas Has this already been covered in another issue?

**Comment by matthewpaulthomas** [comment] 2020-10-20 12:06
Yes, this is a duplicate of #8392.

**Closed by matthewpaulthomas** 2020-10-20 12:06 UTC
Labels: Priority: High, Shop QA testing 🛒
