### ISSUE TITLE
[Webinar] [Android in the cloud] - Build takeover and engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6844] opened 2020-02-24 14:44 UTC
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/19HsZx5SCw9nKq2AXklGAvHJoFp2DJ-g6cEe0vP7JWCw/edit#gid=0) and [design](2400):
 
- [ ] build takeover
- [ ] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] remove `takeovers/_anbox-takeover.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by sowasred2012** [comment] 2020-02-25 10:24
@pmahnke I think this is a dupe of @pmahnke I think this is a dupe of https://app.zenhub.com/workspaces/web--ubuntu-clan-5931746dba512f05402b61f6/issues/canonical-web-and-design/ubuntu.com/6843

**Comment by anasereijo** [comment] 2020-02-25 12:44
@sowasred2012 this is ready for you https://github.com/canonical-web-and-design/web-squad/issues/2400

**Closed** 2020-02-25 17:15 UTC

**Comment by pmahnke** [comment] 2020-02-26 19:16
![](https://github.trello.services/images/mini-trello-icon.png) [Webinar - Android in the cloud](https://trello.com/c/Qr9d067G/699-webinar-android-in-the-cloud)
