### ISSUE TITLE
Order of subscriptions changes when i ua attach

### ISSUE THREAD

**Issue by alesstimec** [canonical-web-and-design/ubuntu.com#8723] opened 2020-11-11 17:22 UTC
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Created a new Subscription. The order of show subscriptions was:

ALESSTIMEC-QA | UA PLAN | ATTACHED | ESM | LIVEPATCH | CERTIFICATIONS
-- | -- | -- | -- | -- | --
*New* UA Infrastructure - Standard (Virtual)  Open | Standard | 0/2 Open | Infra Open | Open | Open | Created on:11 November 2020Ends:11 November 2021 | Created on: | 11 November 2020 | Ends: | 11 November 2021
Created on: | 11 November 2020
Ends: | 11 November 2021
uaa-testing-4  Open | Advanced | 0 Open | Infra Open | Open | Open
uaa-testing-2  Open | Advanced | 0 Open | Infra Open | Open | Open
uaa-testing  Open | Advanced | 1 Open | Infra Open | Open | Open
uaa-testing-3  Open | Advanced | 0 Open | Infra Open | Open | Open

Then i attach a machine to the first subscription (UA Infrastructure) and the order changes to 

ALESSTIMEC-QA | UA PLAN | ATTACHED | ESM | LIVEPATCH | CERTIFICATIONS
-- | -- | -- | -- | -- | --
*New* uaa-testing-4  Open | Advanced | 0 Open | Infra Open | Open | Open
uaa-testing-2  Open | Advanced | 0 Open | Infra Open | Open | Open
uaa-testing  Open | Advanced | 1 Open | Infra Open | Open | Open
uaa-testing-3  Open | Advanced | 0 Open | Infra Open | Open | Open
UA Infrastructure - Standard (Virtual)  Open | Standard | 1/2 Open | Infra Open | Open | Open

Notice, that the new subscription is now last in the list. And an old subscription is now marked as "new".

## Process

1. Create multiple subscriptions
2. attach a machine to the subscription marked as "new"
3. check the order of subscription on the shop page.

## Current and expected result

The order of subscriptions changed and an old subscription was marked as "new". I would expect the order to remain the same.

## Screenshot

![Before](https://user-images.githubusercontent.com/5555154/98843089-c79bfa00-244a-11eb-9722-e25db850a9d6.png)
![After](https://user-images.githubusercontent.com/5555154/98843110-cd91db00-244a-11eb-8dfc-8f6c9c47ebc5.png)

## Browser details

Brave

**Comment by sowasred2012** [comment] 2020-11-11 17:33
Aha, I see what the issue is. On page load, we parse the list of subscriptions you have, and look for the most recent subscription that doesn't have any machines attached. If we find any, we float the most recent one to the top of the table and give you instructions on how to attach machines to the subscription.

This is technically working as intended, since you saw the subscription you just purchased at the top of the list initially, then attached a machine, making it no longer "new" and instead highlighting another subscription that has zero machines attached. 

That said, I can see that this would feel like an odd experience. @matthewpaulthomas could we get your thoughts?

**Comment by matthewpaulthomas** [comment] 2020-11-20 13:37
[From the spec](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.7tpr8idpiheg):
> A subscription should be considered as “new” when all of these are true:
> - it is associated with an account (and if necessary, an organisation)
> - you have never attached any machines to it
> - you have not yet added a newer subscription.

(The first item is moot, since we don’t have that feature yet.)

> On page load, we parse the list of subscriptions you have, and look for the most recent subscription that doesn't have any machines attached. If we find any, we float the most recent one to the top of the table

That nearly matches the spec … but not quite. This would be better:

> On page load, we parse the list of subscriptions you have, and look for the most recent subscription. If it doesn’t have any machines attached, we float it to the top of the table

It still wouldn’t be _completely_ correct, because we want “never attached any machines” rather than “doesn’t have any machines attached”, but it would be correct most of the time, including fixing this case.

**Comment by wgx** [comment] 2021-11-02 13:50
This is resolved in the new /advantage UI, closing.

**Closed by wgx** 2021-11-02 13:50 UTC
Labels: Priority: Low, Commercial 🛒
