### ISSUE TITLE
Visiting author page does not display the latest posts

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7048] opened 2020-03-20 21:49 UTC
Visit https://ubuntu.com/blog/canonical-managed-services-ubuntu-support-covid-19
Click on the author
The author page does not display latest posts
The second page crashes the site.

---
*Reported from: https://ubuntu.com/blog/canonical-managed-services-ubuntu-support-covid-19*

**Comment by sowasred2012** [comment] 2020-03-23 09:30
@anthonydillon I've tried to reproduce this, but can see both latest posts and a second page - is it still happening for you?

**Comment by anthonydillon** [comment] 2020-03-23 11:05
@sowasred2012 I am referring to the fact the covid post is not available on marks profile: https://ubuntu.com/blog/author/mark-shuttleworth

**Comment by SirSamTumless** [comment] 2020-05-06 15:36
This issue is due to the fact that Mark has many accounts on WordPress, closing due to staleness.

**Closed by SirSamTumless** 2020-05-06 15:36 UTC
